### PR TITLE
Add chart-show-diff-only flag to collapse the equal coverage results

### PR DESCRIPTION
**Pull request by mgerasimchuk**
As a user of the action I want to avoid the loosing my coverage changes chart in case when I push 20+ commits with the same coverage value

### CODE REVIEW

**Comment by ncruces** [comment]
I want it too. I mean, I often edit the wiki manually to avoid this.

But, eventually… this will have like 200 configuration knobs. 🤣

**Comment by mgerasimchuk** [comment]
>I want it too. I mean, I often edit the wiki manually to avoid this.

:D

>But, eventually… this will have like 200 configuration knobs. 🤣

So, yup, looks like the list of parameters can be huge, especially regarding the chart settings))

Anyway, feel free to close MR if it not match your roadmap))

**Comment by ncruces** [comment]
I'm considering a few things:
- where do I draw the line?
- this seems like a better default, actually…
- could/should this be done in `jq` rather than `awk`?

There's also the fact that the chart likely merits a refactor. Most users don't use it, so I probably shouldn't be storing an ever growing log when they have it disabled (and making this [line](https://github.com/ncruces/go-coverage-report/blob/57ac6f0f19874f7afbab596105154f08004f482e/push.sh#L9) useless because I _always_ have changes).

This is to good to just drop, so I'll let it sit while I think it through.

**Comment by ncruces** [comment]
Added this by default in:
https://github.com/ncruces/go-coverage-report/blob/a12281c449c691078b2f4b6d39f2b3ae51a680cc/coverage.sh#L54-L58

Thanks!

**Pull request closed without merging**
